basePath: /api/v1
definitions:
  Dashboard:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      metadata:
        $ref: '#/definitions/DashboardMetadata'
      updatedAt:
        type: string
      widgets:
        items:
          $ref: '#/definitions/DashboardWidget'
        type: array
    type: object
  DashboardMetadata:
    properties:
      createdAt:
        type: string
      dashboardId:
        type: integer
      description:
        type: string
      displayName:
        type: string
      headerImage:
        items:
          type: integer
        type: array
      id:
        type: integer
      tags:
        items:
          $ref: '#/definitions/DashboardTag'
        type: array
      updateAt:
        type: string
    type: object
  DashboardTag:
    properties:
      bgColor:
        type: string
      createdAt:
        type: string
      dashboardMetadataId:
        type: integer
      displayName:
        type: string
      id:
        type: integer
      textColor:
        type: string
      updatedAt:
        type: string
    type: object
  DashboardWidget:
    properties:
      createdAt:
        type: string
      dashboardId:
        type: integer
      description:
        type: string
      displayName:
        type: string
      id:
        type: integer
      location:
        $ref: '#/definitions/DashboardWidgetLocation'
      locationId:
        type: integer
      updatedAt:
        type: string
      widget:
        $ref: '#/definitions/Widget'
      widgetId:
        type: integer
    type: object
  DashboardWidgetLocation:
    properties:
      MaxWidth:
        type: integer
      createdAt:
        type: string
      height:
        type: integer
      id:
        type: integer
      maxHeight:
        type: integer
      minHeight:
        type: integer
      minWidth:
        type: integer
      updatedAt:
        type: string
      width:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  Widget:
    properties:
      id:
        type: string
      installPath:
        type: string
      widgetJSON:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Documentation for the exposed HTTP API.
  title: Toolboard API
  version: "1.0"
paths:
  /dashboard:
    post:
      consumes:
      - application/json
      description: Stores the body dashboard object as a new entry in the database
      operationId: post-dashboard
      parameters:
      - description: The dashboard to create
        in: body
        name: dashboard
        required: true
        schema:
          $ref: '#/definitions/Dashboard'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Dashboard'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new Dashboard
      tags:
      - dashboard
    put:
      consumes:
      - application/json
      description: Stores the dashboard object into the database with the same ID.
      operationId: put-dashboard
      parameters:
      - description: The dashboard to update
        in: body
        name: dashboard
        required: true
        schema:
          $ref: '#/definitions/Dashboard'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Dashboard'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update an existing Dashboard
      tags:
      - dashboard
  /dashboard/{id}:
    delete:
      description: Checks the ID in the database, and deletes that entry if present
      operationId: delete-dashboard
      parameters:
      - description: Dashboard ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      summary: Delete a dashboard
      tags:
      - dashboard
  /dashboard/all:
    get:
      description: Returns one json object with all dashboards in the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Dashboard'
            type: array
        "500":
          description: Internal Server Error
      summary: Get all dashboards
      tags:
      - dashboard
  /widget/{id}:
    get:
      description: Returns a json object of the Widget with the smae ID
      parameters:
      - description: Widget ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Widget'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get widget by ID
      tags:
      - widget
  /widget/all:
    get:
      description: Returns one json object with all available widgets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Widget'
            type: array
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all widgets, locally and externally
      tags:
      - widget
  /widget/embed/{id}/{file}:
    get:
      description: Returns html of the Widget with the smae ID
      parameters:
      - description: Widget ID
        in: path
        name: id
        required: true
        type: string
      - description: Optional file name
        in: path
        name: file
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "415":
          description: Unsupported Media Type
        "500":
          description: Internal Server Error
      summary: Get HTML of a Widget
      tags:
      - widget
swagger: "2.0"
